spring.application.name=api

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/ramen_dojang}
spring.datasource.username=${DATABASE_USERNAME:ramen}
spring.datasource.password=${DATABASE_PASSWORD:ramen}

spring.flyway.enabled=true

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/openapi

management.endpoints.web.exposure.include=health
