spring.application.name=api
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/ramen_dojang}
spring.datasource.username=${DATABASE_USERNAME:ramen}
spring.datasource.password=${DATABASE_PASSWORD:ramen}

spring.flyway.enabled=true

naver.search.client-id=${NAVER_SEARCH_CLIENT_ID:}
naver.search.client-secret=${NAVER_SEARCH_CLIENT_SECRET:}

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/openapi
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json

management.endpoints.web.exposure.include=health
